###########################################################################
#                                                                         #
# Author: Daniel Mock                                                     #
#                                                                         #
# Purpose: To document progress in learning algorithms & data structures  #
#                                                                         #
# References: This question was generated by leetcode.com. The solution   #
# to the question was generated by Daniel Mock.                           #
#                                                                         #
###########################################################################


class Solution:
    def fourSum(self, nums: List[int], target: int) -> List[List[int]]:
        outlist = []
        nums.sort()
        for num1 in range(len(nums)-3):
            max_len = len(nums)-1
            for num2 in range(num1+1,len(nums)-2):
                max_len = len(nums)-1
                for num3 in range(num2+1,len(nums)-1):
                    while nums[num1] + nums[num2] + nums[num3] + nums[max_len] > target:
                        max_len-=1
                        if max_len <= num3: break
                    if max_len <= num3: break
                    if nums[num1] + nums[num2] + nums[num3] + nums[max_len] == target and [nums[num1],nums[num2],nums[num3],nums[max_len]] not in outlist:
                        outlist.append([nums[num1],nums[num2],nums[num3],nums[max_len]])
        return outlist
