###########################################################################
#                                                                         #
# Author: Daniel Mock                                                     #
#                                                                         #
# Purpose: To document progress in learning algorithms & data structures  #
#                                                                         #
# References: This question was generated by leetcode.com. The solution   #
# to the question was generated by Daniel Mock.                           #
#                                                                         #
###########################################################################

class Solution:
    def isValid(self, s: str) -> bool:
        reference_dict = {'(':')', '{':'}', '[':']'}
        open_list = []
        numOpenParen = 0
        for loc, val in enumerate(s):
            if val in ['(', '{', '[']:
                numOpenParen +=1
                open_list.append(reference_dict[val])
            elif val in [')', '}', ']']:
                if numOpenParen > 0:
                    close = open_list.pop()
                    print(f"close: {close}")
                    if val == close:
                        numOpenParen -= 1
                    else:
                        return False
                else:
                    return False
        if numOpenParen == 0:
            return True
        else:
            return False
