###########################################################################
#                                                                         #
# Author: Daniel Mock                                                     #
#                                                                         #
# Purpose: To document progress in learning algorithms & data structures  #
#                                                                         #
# References: This question was generated by leetcode.com. The solution   #
# to the question was generated by Daniel Mock.                           #
#                                                                         #
###########################################################################
"brute force method, O(N). Use binary search for O(logN) complexity."
class Solution:
    def search(self, nums: List[int], target: int) -> int:
        for index, i in enumerate(nums):
            if i == target:
                return index
        return -1
