###########################################################################
#                                                                         #
# Author: Daniel Mock                                                     #
#                                                                         #
# Purpose: To document progress in learning algorithms & data structures  #
#                                                                         #
# References: This question was generated by leetcode.com. The solution   #
# to the question was generated by Daniel Mock.                           #
#                                                                         #
###########################################################################

"Solution Too Slow (N^2?)"
'''
class Solution:
    def productExceptSelf(self, nums: List[int]) -> List[int]:
        output_arr = []
        for elem in nums:
            sub_arr = nums.copy()
            sub_arr.remove(elem)
            multiply_arr = sub_arr.pop(0)
            for val in sub_arr:
                multiply_arr = multiply_arr * val
            output_arr.append(multiply_arr)
        return output_arr
'''
"Same as above but more concise"
'''
import math
class Solution:
    def productExceptSelf(self, nums: List[int]) -> List[int]:
        out = []
        for i in nums:
            arr = nums.copy()
            arr.remove(i)
            out.append(math.prod(arr))
        return out
'''
