###########################################################################
#                                                                         #
# Author: Daniel Mock                                                     #
#                                                                         #
# Purpose: To document progress in learning algorithms & data structures  #
#                                                                         #
# References: This question was generated by leetcode.com. The solution   #
# to the question was generated by Daniel Mock.                           #
#                                                                         #
###########################################################################


class Solution:
    def fizzBuzz(self, n: int) -> List[str]:
        if n is None: return
        output = []
        for num in range(1,n+1):
            if num%15 == 0:
                output.append("FizzBuzz")
            elif num%3 == 0:
                output.append("Fizz")
            elif num%5 == 0:
                output.append("Buzz")
            else:
                output.append(str(num))
        return output
