###########################################################################
#                                                                         #
# Author: Daniel Mock                                                     #
#                                                                         #
# Purpose: To document progress in learning algorithms & data structures  #
#                                                                         #
# References: This question was generated by leetcode.com. The solution   #
# to the question was generated by Daniel Mock.                           #
#                                                                         #
###########################################################################


from collections import defaultdict
class Solution:
    def findDuplicates(self, nums: List[int]) -> List[int]:
        if len(nums) == 0: return []
        output = []
        num_dict = defaultdict(int)
        for num in nums:
            if num in num_dict:
                num_dict[num] = 2
            else: num_dict[num] = 1
        for num in num_dict:
            if num_dict[num] == 2:
                output.append(num)
        return output
