###########################################################################
#                                                                         #
# Author: Daniel Mock                                                     #
#                                                                         #
# Purpose: To document progress in learning algorithms & data structures  #
#                                                                         #
# References: This question was generated by leetcode.com. The solution   #
# to the question was generated by Daniel Mock.                           #
#                                                                         #
###########################################################################


from collections import defaultdict
class Solution:
    def fourSumCount(self, A: List[int], B: List[int], C: List[int], D: List[int]) -> int:
        output = 0
        combo_map = defaultdict(int)
        for a in A:
            for b in B:
                val = a+b
                if val in combo_map:
                    combo_map[val] +=1
                else:
                    combo_map[val] = 1
        for c in C:
            for d in D:
                val = -(c+d)
                if val in combo_map:
                    output+= combo_map[val]
        return output

        #Too slow solution
        '''
        output = 0
        for a in A:
            for b in B:
                for c in C:
                    for d in D:
                        if a + b + c + d == 0:
                            output +=1
        return output
        '''
