###########################################################################
#                                                                         #
# Author: Daniel Mock                                                     #
#                                                                         #
# Purpose: To document progress in learning algorithms & data structures  #
#                                                                         #
# References: This question was generated by leetcode.com. The solution   #
# to the question was generated by Daniel Mock.                           #
#                                                                         #
###########################################################################

# Definition for a binary tree node.
# class TreeNode:
#     def __init__(self, x):
#         self.val = x
#         self.left = None
#         self.right = None

class Solution:
    #Recursive
    def inorderTraversal(self, root: TreeNode) -> List[int]:
        if root is None: return
        lst = []
        return self.recurse(root,lst)

    def recurse(self, root, lst):
        if root is None: return lst

        self.recurse(root.left, lst)
        lst.append(root.val)
        self.recurse(root.right, lst)


        return lst

    '''
        #Iterative
        if root is None: return root
        stack = []
        out = []
        node = root
        while True:
            if node is not None:
                stack.append(node)
                node = node.left
            elif len(stack) > 0:
                node = stack.pop()
                out.append(node.val)
                node = node.right
            else: break
        return out
     '''
