###########################################################################
#                                                                         #
# Author: Daniel Mock                                                     #
#                                                                         #
# Purpose: To document progress in learning algorithms & data structures  #
#                                                                         #
# References: This question was generated by leetcode.com. The solution   #
# to the question was generated by Daniel Mock.                           #
#                                                                         #
###########################################################################

class Solution:
    def searchBST(self, root: TreeNode, val: int) -> TreeNode:
        if root is None: return root
        ptr = root

        while True:
            if val == ptr.val:
                return ptr
            elif val > ptr.val:
                if ptr.right:
                    ptr = ptr.right
                else: return None

            else:
                if ptr.left:
                    ptr = ptr.left
                else: return None
