/*
###########################################################################
#                                                                         #
# Author: Daniel Mock                                                     #
#                                                                         #
# Purpose: To document progress in learning algorithms & data structures  #
#                                                                         #
# References: This question was generated by leetcode.com. The solution   #
# to the question was generated by Daniel Mock.                           #
#                                                                         #
###########################################################################
*/

/**
 * Definition for singly-linked list.
 * struct ListNode {
 *     int val;
 *     struct ListNode *next;
 * };
 */

void swap(int* a, int* b){

    int temp = 0;
    temp = *a;
    *a = *b;
    *b = temp;

}

struct ListNode* swapPairs(struct ListNode* head){
    struct ListNode* temp = head;

    if(head == NULL) return NULL;
    if(head->next == NULL) return head;

    while(temp != NULL && temp->next != NULL){
        swap(&temp->val, &temp->next->val);
        temp = temp->next->next;
    }
    return head;

}
