###########################################################################
#                                                                         #
# Author: Daniel Mock                                                     #
#                                                                         #
# Purpose: To document progress in learning algorithms & data structures  #
#                                                                         #
# References: This question was generated by leetcode.com. The solution   #
# to the question was generated by Daniel Mock.                           #
#                                                                         #
###########################################################################


# Definition for singly-linked list.
# class ListNode:
#     def __init__(self, x):
#         self.val = x
#         self.next = None

class Solution:
    def deleteDuplicates(self, head: ListNode) -> ListNode:
        if head is None:
            return head

        curr = head
        prev = None
        curr_val = head.val
        prev = curr
        curr = curr.next

        while curr:
            if curr.val == curr_val:
                prev.next = curr.next
            else:
                curr_val = curr.val
                prev = curr
            curr = curr.next
        return head
