###########################################################################
#                                                                         #
# Author: Daniel Mock                                                     #
#                                                                         #
# Purpose: To document progress in learning algorithms & data structures  #
#                                                                         #
# References: This question was generated by leetcode.com. The solution   #
# to the question was generated by Daniel Mock.                           #
#                                                                         #
###########################################################################

# Definition for singly-linked list.
# class ListNode:
#     def __init__(self, x):
#         self.val = x
#         self.next = None

class Solution:
    def hasCycle(self, head: ListNode) -> bool:
        if head is None or head.next is None:
            return False
        node = head
        node2 = head.next
        while node != node2:
            if node2 is None or node2.next is None:
                return False
            node = node.next
            node2 = node2.next.next

        return True
        
    #simple visited list populate & check
    '''
    def hasCycle(self, head: ListNode) -> bool:
    if head is None: return False
    if head.next is None: return False
    visited_list = []
    while head:
        if head in visited_list:
            return True
        visited_list.append(head)
        head = head.next
    return False
    '''
