###########################################################################
#                                                                         #
# Author: Daniel Mock                                                     #
#                                                                         #
# Purpose: To document progress in learning algorithms & data structures  #
#                                                                         #
# References: This question was generated by leetcode.com. The solution   #
# to the question was generated by Daniel Mock.                           #
#                                                                         #
###########################################################################

"Dynamic Programming solution"
class Solution:
    def maxProduct(self, nums: List[int]) -> int:

        temp_max_pos = 1
        temp_max_neg = 1
        max_pos = 1
        max_neg = 1
        output = -math.inf

        for val in nums:
            temp_max_pos = max(val, val*max_pos, val*max_neg)
            temp_max_neg = min(val, val*max_pos, val*max_neg)
            max_pos = temp_max_pos
            max_neg = temp_max_neg
            if max_pos > output:
                output = max_pos
        return output
